//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterListCreationTool.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharacterListCreationTool.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race bonus.
        /// </summary>
        public static string DnD5eRaceCustomBonus {
            get {
                return ResourceManager.GetString("DnD5eRaceCustomBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragonborn.
        /// </summary>
        public static string DnD5eRaceDragonborn {
            get {
                return ResourceManager.GetString("DnD5eRaceDragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf.
        /// </summary>
        public static string DnD5eRaceDwarf {
            get {
                return ResourceManager.GetString("DnD5eRaceDwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elf.
        /// </summary>
        public static string DnD5eRaceElf {
            get {
                return ResourceManager.GetString("DnD5eRaceElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnome.
        /// </summary>
        public static string DnD5eRaceGnome {
            get {
                return ResourceManager.GetString("DnD5eRaceGnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-elf.
        /// </summary>
        public static string DnD5eRaceHalfElf {
            get {
                return ResourceManager.GetString("DnD5eRaceHalfElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halfling.
        /// </summary>
        public static string DnD5eRaceHalfling {
            get {
                return ResourceManager.GetString("DnD5eRaceHalfling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-orc.
        /// </summary>
        public static string DnD5eRaceHalfOrc {
            get {
                return ResourceManager.GetString("DnD5eRaceHalfOrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string DnD5eRaceHuman {
            get {
                return ResourceManager.GetString("DnD5eRaceHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string DnD5eRaceTabRace {
            get {
                return ResourceManager.GetString("DnD5eRaceTabRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subrace.
        /// </summary>
        public static string DnD5eRaceTabSubrace {
            get {
                return ResourceManager.GetString("DnD5eRaceTabSubrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiefling.
        /// </summary>
        public static string DnD5eRaceTiefling {
            get {
                return ResourceManager.GetString("DnD5eRaceTiefling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Dragonborn.
        /// </summary>
        public static string DnD5eSubraceBlackDragonborn {
            get {
                return ResourceManager.GetString("DnD5eSubraceBlackDragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Dragonborn.
        /// </summary>
        public static string DnD5eSubraceBlueDragonborn {
            get {
                return ResourceManager.GetString("DnD5eSubraceBlueDragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brass Dragonborn.
        /// </summary>
        public static string DnD5eSubraceBrassDragonborn {
            get {
                return ResourceManager.GetString("DnD5eSubraceBrassDragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Dragonborn.
        /// </summary>
        public static string DnD5eSubraceBronzeDragonborn {
            get {
                return ResourceManager.GetString("DnD5eSubraceBronzeDragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper Dragonborn.
        /// </summary>
        public static string DnD5eSubraceCopperDragonborn {
            get {
                return ResourceManager.GetString("DnD5eSubraceCopperDragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drow.
        /// </summary>
        public static string DnD5eSubraceDrowElf {
            get {
                return ResourceManager.GetString("DnD5eSubraceDrowElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest Gnome.
        /// </summary>
        public static string DnD5eSubraceForestGnome {
            get {
                return ResourceManager.GetString("DnD5eSubraceForestGnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Dragonborn.
        /// </summary>
        public static string DnD5eSubraceGoldDragonborn {
            get {
                return ResourceManager.GetString("DnD5eSubraceGoldDragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Dragonborn.
        /// </summary>
        public static string DnD5eSubraceGreenDragonborn {
            get {
                return ResourceManager.GetString("DnD5eSubraceGreenDragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Elf.
        /// </summary>
        public static string DnD5eSubraceHighElf {
            get {
                return ResourceManager.GetString("DnD5eSubraceHighElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Dwarf.
        /// </summary>
        public static string DnD5eSubraceHillDwarf {
            get {
                return ResourceManager.GetString("DnD5eSubraceHillDwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightfoot Halfling.
        /// </summary>
        public static string DnD5eSubraceLightfootHalfling {
            get {
                return ResourceManager.GetString("DnD5eSubraceLightfootHalfling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Dwarf.
        /// </summary>
        public static string DnD5eSubraceMountainDwarf {
            get {
                return ResourceManager.GetString("DnD5eSubraceMountainDwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Dragonborn.
        /// </summary>
        public static string DnD5eSubraceRedDragonborn {
            get {
                return ResourceManager.GetString("DnD5eSubraceRedDragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Gnome.
        /// </summary>
        public static string DnD5eSubraceRockGnome {
            get {
                return ResourceManager.GetString("DnD5eSubraceRockGnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Dragonborn.
        /// </summary>
        public static string DnD5eSubraceSilverDragonborn {
            get {
                return ResourceManager.GetString("DnD5eSubraceSilverDragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stout Halfling.
        /// </summary>
        public static string DnD5eSubraceStoutHalfling {
            get {
                return ResourceManager.GetString("DnD5eSubraceStoutHalfling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Dragonborn.
        /// </summary>
        public static string DnD5eSubraceWhiteDragonborn {
            get {
                return ResourceManager.GetString("DnD5eSubraceWhiteDragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Elf.
        /// </summary>
        public static string DnD5eSubraceWoodElf {
            get {
                return ResourceManager.GetString("DnD5eSubraceWoodElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string MainWindowGame {
            get {
                return ResourceManager.GetString("MainWindowGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DnD5e.
        /// </summary>
        public static string MainWindowGameDnD5e {
            get {
                return ResourceManager.GetString("MainWindowGameDnD5e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathfinder.
        /// </summary>
        public static string MainWindowGamePathfinder {
            get {
                return ResourceManager.GetString("MainWindowGamePathfinder", resourceCulture);
            }
        }
    }
}
